### ISSUE TITLE
大佬 iPhone14 的抢购可以用这种方式吗

### ISSUE THREAD

**Issue by lamking** [geeeeeeeek/jd-seckill-2022#3]

**Comment by geeeeeeeek** [comment]
可以吧，流程差不多

**Comment by Almustaaafaaa** [comment]
我用卡订单-取消-抢购的方式测了, 完全可以抢到

**Comment by papa-cmd** [comment]
能给个详细教程吗，抢了好几天手机没抢到

**Comment by anysoft** [comment]
抢购分为几种模式：
1. 普通商品无货，定时查询库存蹲抢
2. 普通商品定时发售(库存由0变为有货)，定时提前构造订单请求抢

3. 预售商品(需要先预约)，可以加入购物车，通过购物车结算。这种用常规购物车结算订单接口就行，当然也可以用抢购接口。
> 这种体现为可以加购，抢购时候显示两个按钮，`加入购物车(黄色)`和`立即购买(淡绿色)`。
4. 预售商品(需要先预约)，无法加入购物车，电脑端无法预约，必须手机端预约。这种采用`https://marathon.jd.com/seckillnew/orderService/submitOrder.action` 接口完成抢购，有完整流程验证和tokenKey(sign)，sk验证。
> 这种体现为 无法加入购物车，必须手机端才能预约，可购买时候只显示一个红色按钮`立即抢购`

**Comment by steelxiang** [comment]
> 
submitOrder.action中的sk你搞定了，能分享下吗

**Comment by anysoft** [comment]
> 可以吧，流程差不多



> 我用卡订单-取消-抢购的方式测了, 完全可以抢到

理论上没问题，但是实践不好说，有人用这个脚本抢到过么？
我自己根据DD得项目改写固化sign去gentoken的抢购日志基本都是90008 偶尔90013

我又根据这个仓库的改了下流程和skuid抢购基本是90013 偶尔90016
到目前没抢到过任何东西。

大体流程是对的，就怕jd埋点，一些忽略的流程会导致请购被动失败，但是又不告诉你错误。
抓包流程 还有get https://tak.jd.com/a/tr.js?_t  一些访问资源的请求不晓得会不会被埋点。


大佬的sign完全可以过，只要有时间分析所有接口，可以完全使用app的全套接口去做脚本。我看github也有人用 python 模拟加载so 或者java模拟加载so完成签名的。

**Comment by steelxiang** [comment]
> > 可以吧，流程差不多
> 
> > 我用卡订单-取消-抢购的方式测了, 完全可以抢到
> 
> 理论上没问题，但是实践不好说，有人用这个脚本抢到过么？ 我自己根据DD得项目改写固化sign去gentoken的抢购日志基本都是90008 偶尔90013
> 
> 我又根据这个仓库的改了下流程和skuid抢购基本是90013 偶尔90016 到目前没抢到过任何东西。
> 
> 大体流程是对的，就怕jd埋点，一些忽略的流程会导致请购被动失败，但是又不告诉你错误。 抓包流程 还有get https://tak.jd.com/a/tr.js?_t 一些访问资源的请求不晓得会不会被埋点。
> 
> 大佬的sign完全可以过，只要有时间分析所有接口，可以完全使用app的全套接口去做脚本。我看github也有人用 python 模拟加载so 或者java模拟加载so完成签名的。

为啥我用抓包gettoken接口拿到tokenkey请求是未登录

**Comment by steelxiang** [comment]
> > 可以吧，流程差不多
> 
> > 我用卡订单-取消-抢购的方式测了, 完全可以抢到
> 
> 理论上没问题，但是实践不好说，有人用这个脚本抢到过么？ 我自己根据DD得项目改写固化sign去gentoken的抢购日志基本都是90008 偶尔90013
> 
> 我又根据这个仓库的改了下流程和skuid抢购基本是90013 偶尔90016 到目前没抢到过任何东西。
> 
> 大体流程是对的，就怕jd埋点，一些忽略的流程会导致请购被动失败，但是又不告诉你错误。 抓包流程 还有get https://tak.jd.com/a/tr.js?_t 一些访问资源的请求不晓得会不会被埋点。
> 
> 大佬的sign完全可以过，只要有时间分析所有接口，可以完全使用app的全套接口去做脚本。我看github也有人用 python 模拟加载so 或者java模拟加载so完成签名的。

为啥我用抓包gettoken接口拿到tokenkey请求是未登录

**Comment by anysoft** [comment]
> > > 可以吧，流程差不多
> > 
> > > 我用卡订单-取消-抢购的方式测了, 完全可以抢到
> > 
> > 理论上没问题，但是实践不好说，有人用这个脚本抢到过么？ 我自己根据DD得项目改写固化sign去gentoken的抢购日志基本都是90008 偶尔90013
> > 
> > 我又根据这个仓库的改了下流程和skuid抢购基本是90013 偶尔90016 到目前没抢到过任何东西。

gentoken是需要body验签的，如果验签不对，返回的tokenkey只有49位，正确的是71位。另外我测试发现，复用固化sign重放请求拿到的tokenkey是71位，但是走流程基本是90008，我仔细看了数据很多数据ua里带ts,ep也带ts，这些都不能固化参数，如果服务端检测参数请求基本就抢不到。

有兴趣一起深入交流，刚建的。t.me/seckillscripts

**Comment by ANMP0042** [comment]
> 
也就是说预约商品抢购都可以用https://marathon.jd.com/seckillnew/orderService/submitOrder.action
