### ISSUE TITLE
captcha验证和最后的resultCode

### ISSUE THREAD

**Issue by Almustaaafaaa** [geeeeeeeek/jd-seckill-2022#4]
我今天测试的时候,captcha验证一直能通过,即使不在抢购时间也可以(也就是12:00之前以及12:30之后),然而突然captcha验证就不能通过了.另外在captcha验证出现问题之前,最后的submitOrder返回的json中,resultCode是90018,但是我自己用手机正常操作抓包得到的都是90008或者90016,参考网上其他人也是这两个情况,.
想问下您有没有类似经验.

**Comment by P3R5T7U9** [comment]
> 我今天测试的时候,captcha验证一直能通过,即使不在抢购时间也可以(也就是12:00之前以及12:30之后),然而突然captcha验证就不能通过了.另外在captcha验证出现问题之前,最后的submitOrder返回的json中,resultCode是90018,但是我自己用手机正常操作抓包得到的都是90008或者90016,参考网上其他人也是这两个情况,. 想问下您有没有类似经验.

时隔8个月，挖下；

不知老哥你之后解决这个问题了么？？我近期才开始研究茅台抢购流程，才翻到这个参考项目库，也遇到captcha验证和最后的resultcode不正常问题，不知如何解决。。。

如果老哥你之后已解决的话，麻烦回复下解决方法呗

**Comment by javashub** [comment]
已经收到您的邮件，谢谢！祝您生活愉快！
